server:
  port: 8070
logging:
  level:
    root: debug
spring:
  application:
    name: gatewayServe
  cloud:
    #    nacos:
    #      discovery:
    #        server-addr: 121.43.152.126:8848
    gateway:
      routes:
        - id: gateway
          uri: http://localhost:8070
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
        - id: base
          uri: http://localhost:8081
          predicates:
            - Path=/base/**
          filters:
            - StripPrefix=1
        - id: sale
          uri: http://localhost:8086
          predicates:
            - Path=/sale/**
          filters:
            - StripPrefix=1
        - id: warehouse
          uri: http://localhost:8085
          predicates:
            - Path=/warehouse/**
          filters:
            - StripPrefix=1
        - id: procurement
          uri: http://localhost:8084
          predicates:
            - Path=/procurement/**
          filters:
            - StripPrefix=1
        - id: system
          uri: http://localhost:8088
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: finance
          uri: http://localhost:8088
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: sa-token
  # token有效期，单位秒，-1代表永不过期
  timeout: 3600
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
gateway-config:
  open-token: false
  open-replay: false